### ISSUE TITLE
Add records to the database

### ISSUE THREAD

**Issue by bethanyhull** [cs481-ekh/f21-famada#1]
Given a working app user should be able to add records to the database

REQUIREMENTS:
- [ ] A database schema will be created to accommodate all the columns requested by sponsor #2 

- [ ] Build gui with the option to add each field by hand organized by table #3

- [ ] Add error checking to the user input fields (type, length, etc.) #4

- [ ] When clicking the “Add” button in the UI a query will be generated to add the field to database #5

- [ ] The sensitive information will be encrypted in the database #6

- [ ] Test for adding records to the database #32 

DOD:
A user can add a record to the database and search for it from the search and view page and find it.
