### ISSUE TITLE
Create menu wrapper

### ISSUE THREAD

**Issue by bethanyhull** [cs481-ekh/f21-famada#18]
Given a page the user will be able to open a menu to navigate to the various pages and view the name of the app

- [x] UI of the wrapper #19 
- [x] link the pages to the buttons #20 
- [x] logic to log out #23 
- [x] test to log out #24 
DOD:
A user will be able to navigate to placeholders of all the pages, logout to return to the login screen, and view the name of the app .
