### ISSUE TITLE
Login page and password

### ISSUE THREAD

**Issue by bethanyhull** [cs481-ekh/f21-famada#7]
A user should be able to log into the app via a password and the app will not be able to be accessed without it.

Requirements:

- [x] A UI is created with a password field. #8 #15 
- [x] View is created to manage password #11 
- [x] Testing to assure that users cannot access pages without logging in. #10 
- [x] If password is entered incorrectly, user is prompted to reenter password #12
