### ISSUE TITLE
General Tests

### ISSUE THREAD

**Issue by austenhale** [cs481-ekh/f21-famada#70]
- [ ] Test for invalid input on field forms #73
- [ ] Test for deleting a value #75
- [ ] Test for adding classes for valid and invalid adjunct members #76 
- [ ] Test for ensuring that duplicate employee IDs are not allowed #78
